### ISSUE TITLE
renderAfterDocumentEvent does not get capture the event early enough

### ISSUE THREAD

**Issue by b12f** [Tribex/prerenderer#5]
I currently have a vue / typescript project set up where I want to prerender two different routes:

```
// webpack.prod.conf.js

new PrerenderSpaPlugin({
        // Absolute path to compiled SPA
        staticDir: config.build.assetsRoot,
        // List of routes to prerender
        routes: [ '/', '/contact' ],

        renderer:  new PrerenderSpaPlugin.PuppeteerRenderer({
          renderAfterDocumentEvent: 'prerender-page-ready',
          injectProperty: '__PRERENDER_INJECTED',
          inject: {
            // Update src/window-shim.d.ts if you change this
            USER_ID: process.argv[2] || 'test-id',
            PRERENDER_PAGE_EVENT: 'prerender-page-ready'
          }
        })
      })
```
The app starts into the main `App.vue` component, which 

* loads data from an API asynchronously, 
* shows (with a `v-if`) the `router-view` when the call finishes, 
* and emits the event with name `__PRERENDER_INJECTED.PRERENDER_PAGE_EVENT` on `document` in the `mounted` hook of the components loaded by the router.

I have setup an eventlistener in the mounted hook of the `App.vue`, which works and logs the event when it comes in:

```
// App.vue

mounted() {
    console.log(PRERENDER_PAGE_EVENT);
    document.addEventListener(PRERENDER_PAGE_EVENT, (ev) => {console.log(ev)});
    axios.get(`${API_URL}/api/${ID}`)
      .then((res) => {
        this.title = res.data.title;
      })
      .catch(() => {
        this.title = 'An error occurred';
      });
  }
```
![prerender-console](https://user-images.githubusercontent.com/11312895/36025777-90082fde-0d94-11e8-8817-85c35fdd001b.png)

However, the prerenderer does not seem to take notice and the build hangs indefinitely. When I emit the event by hand from the devtools console, the respective tab closes and the correctly rendered version of the html is saved.

In the routed page components, changing the following:
```
  // Contact.vue

  mounted() {
    this.$nextTick(() => {
      document.dispatchEvent(new Event(PRERENDER_PAGE_EVENT));
    });
  }
```
To this:
```
  // Contact.vue

  mounted() {
    this.$nextTick(() => {
      setTimeout(() => {
        document.dispatchEvent(new Event(PRERENDER_PAGE_EVENT));
      }, 500);
    });
  }
```
Makes the build succeed, but feels very hacky.

Tested on Debian.

**Comment by b12f** [comment]
I've looked through the code, and the problem might be here: https://github.com/Tribex/prerenderer/blob/master/renderers/renderer-puppeteer/es6/renderer.js#L95

Moving this up before the `page.goto` and using `page.evaluateOnNewDocument` might fix it

**Comment by Tribex** [comment]
@b12f Good idea. Thanks for spotting that!

**Comment by Tribex** [comment]
Should be fixed in `0.6.3`. If something else pops up, let me know.

**Comment by b12f** [comment]
I'll spin this version up for a test now

**Comment by b12f** [comment]
AFAIK, this still does not work. This part didn't really change:

https://github.com/Tribex/prerenderer/blob/master/renderers/renderer-puppeteer/es6/renderer.js#L109

The problem is that inbetween the page.goto and page.evaluate the rendering process has already finished and has emitted the event. I was working on a solution where there is an extra call to `evaluateOnNewDocument`, which set a `Promise` on the `window[options.injectProperty]`, that resolved as soon as the event was captured. That way, in `waitForRender` you can just wait for the Promise to resolve, which will happen even if the event already fired. Feels kinda hacky too, but I'm not sure how else to solve it.

**Comment by Tribex** [comment]
@b12f Drat. Was in a hurry and didn't have time to test. I'll have to take a look in-depth tomorrow. I didn't go with your solution just because it seemed like it would take more effort. I'll try something similar to that tomorrow.

**Comment by b12f** [comment]
Updated above comment^

Thanks for the quick responses!

**Comment by Tribex** [comment]
Makes sense, but yeah, definitely looks hacky. 

You're welcome! I'll try and fix it in the morning.

**Comment by Tribex** [comment]
@b12f Okay, should be fixed for real now, I tested. Used a variant of your solution that just sets a boolean property.

**Comment by b12f** [comment]
0.6.4 is not available on npm, just 0.6.3

```
$ npm update
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @prerenderer/prerenderer@^0.6.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'prerender-spa-plugin'
```

**Comment by Tribex** [comment]
@b12f Oi. NPM link strikes again.

My apologies for all the trouble. Been a bit frazzled the past couple days.

**Comment by b12f** [comment]
@Tribex I copy pasted the code into `prerenderer-puppeteer/es6` and it seems to work. Going to try with the npm version now. Don't worry btw, your response has been great!

**Comment by b12f** [comment]
Yus, NPM version works! I think doing it with a promise instead of setting basically the same event listener twice feels _less_ hacky however, cause that's kinda what promises were made for.

**Comment by Tribex** [comment]
@b12f Yeah, It's what they're made for, but it also makes the code a bit more confusing. I opted for what I thought was the simplest solution. :3
